services:
  dashboard:
    build:
      context: .
      dockerfile: ./prod.dashboard.Dockerfile
      args:
        - WS_URL=$WS_URL
    ports:
      - 80
    restart: unless-stopped

  api:
    build:
      context: ./api
      dockerfile: ../prod.node.Dockerfile
      args:
        - LOG_FILE=$LOG_FILE
        - SERVER_NAME=$SERVER_NAME
        - GEO_COORDS=$GEO_COORDS
    ports:
      - 3000
    volumes:
      - /var/log/auth.log:/app/auth.log
    restart: unless-stopped
