services:
  dashboard:
    build:
      context: .
      dockerfile: ./prod.dashboard.Dockerfile
      args:
        - WS_URL=$WS_URL
    # command: pnpm preview
    # command: envsubst > /var/www/html/index.html && nginx -g daemon off
    ports:
      - 80
    # volumes:
    #   - ./:/app
    #   - /node_modules
    restart: unless-stopped

  api:
    build:
      context: ./api
      dockerfile: ../prod.node.Dockerfile
      args:
        - LOG_FILE=$LOG_FILE
        - SERVER_NAME=$SERVER_NAME
        - GEO_COORDS=$GEO_COORDS
    ports:
      - 3000
    # volumes:
    #   - ./:/app
    #   - /node_modules
    restart: unless-stopped
